### ISSUE TITLE
Enhance client server communication 

### ISSUE THREAD

**Issue by NesbiDevelopment** [chreul/LAREX#102]
As a next step we plan to restructure parts of the client server communication since the current solution lacks modularity which already caused some issues in the past. Performing these modifications will probably take 1-2 months. However, with these changes made, the realization of the next two planned milestones (segmenting by component selection and vastly improved editing/post correction options) should become a lot easier.

**Comment by andbue** [comment]
Maybe this solves my issue, so I'll just mention it here instead of opening a new bug report:
If I open several books in tabs at the same time (tested in Firefox) and load existing segmentation, sometimes a client gets the wrong data. That means, segmentation data for the wrong book is put over the page image. I haven't tested if it's possible to completely take over a book from another computer, but somehow the session handling seems to have some issues at the moment.

**Comment by NesbiDevelopment** [comment]
Hi there, yes the new server communication should solve your issue.

**Comment by NesbiDevelopment** [comment]
The branch has now been merged with master.

Created a better separation between client and server.
Segmentations are no longer saved at the server session, which results in a more flexible client editor features.

The application should now be more stable to handle multiple instances on one client.

Fixed segments and result segments are no longer separated. Editing them is now more fluent.
Result segments can now edited like fixed segments and combining segments is no longer dependent on the segment type. Every segment can now be fixed via the shortcut "f" or by clicking the "fix segment"-button

It's now easier to export the current visual state.

There have also been small enhancements, like waking the canvas after the browser tab got to sleep.
