### ISSUE TITLE
error when adding images at runtime

### ISSUE THREAD

**Issue by jze** [chreul/LAREX#32]
If a new images is added to a book diretory while LAREX is running and the book is open in the LAREX editor, an exception is thrown when clicking on the new image (or the last image of the book):
java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at com.web.model.Book.getPage(Book.java:46)
	at com.web.facade.LarexFacade.segmentPages(LarexFacade.java:106)
	at com.web.controller.ViewerController.segment(ViewerController.java:86)

**Comment by NesbiDevelopment** [comment]
Thank you for the detailed description. Changing the books on runtime is not as stable as it should be.
The segmentation results of each page since the last complete segmentation (Pressing the "Segment" button) are stored in the user session. This has many advantages for the tool but can cause problems when the books are changed or the session has run out.

I will test this issue further and work on a solution that keeps the advantages while offering a more fluent experience.

**Comment by NesbiDevelopment** [comment]
It should now be possible to add and remove books and pages at runtime without any exception.
Reloading the webpage will show the changes to the library and books.
Trying to segment a removed page will mark it as removed and display a cached version without any segmentation.
