### ISSUE TITLE
Question: How is the `Reading Order` functionality used?

### ISSUE THREAD

**Issue by wrznr** [chreul/LAREX#77]
Using the current master, I see two new “buttons”: One hat the right side named `Reading Order`, the other in the top menu bar named `Order`. Both are clickable but seem to be without function at the moment (i.e. nothing happens when they are clicked). The assumed functionality would be highly appreciated! Am I doing something wrong or is the functionality not yet implemented/activated?

**Comment by NesbiDevelopment** [comment]
Hello wrznr. Yes the functionality to create a reading order has been added to master. (With a minor bug that is being looked into atm #76).

It's sounds like you are experiencing a browser side caching problem.
You may be on master, but your browser probably still loads the old javascript files from cache.

To resolve this, please press ctrl+shift+r. The page should then automatically reload, drop the cache and load the most recent javascript files.
If it does not reload, than please move your mouse away from the main canvas. It could intercept with the short cut.

**Comment by NesbiDevelopment** [comment]
Ps.: The functionality of creating/editing a reading order is currently still being worked on, but has been added, because of high demand.
Changes in the GUI regarding the reading order are to be expected in the future.

It currently works as follows:
Two buttons on the main menu should appear when opening the tab 'Reading Order'.
The left one is to set a reading order by hand. Selecting segments will add them to the reading order, in the order they are clicked on. Right click or clicking the button again will end this mode and save the reading order.

The button on the right will automatically set a reading order for you.

After/while creating a reading order, it should be displayed on the canvas, as well as a list on the right.
The elements on the right can be rearranged via drag and drop.

**Comment by wrznr** [comment]
Works like a charm. Thanks!
